name: Format
on: [push]
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10.x, 3.11]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make install
    - name: Format code with Python Black
      run: |
        make format